# Generated by Django 4.2.23 on 2025-08-18 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время должно быть больше 0')], verbose_name='Время приготовления (мин)'),
        ),
    ]
